// <auto-generated />
namespace SquadClock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmplStoredProc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmplStoredProc));
        
        string IMigrationMetadata.Id
        {
            get { return "201508181017212_EmplStoredProc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
