//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTemplate
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetItem
    {
        public int Id { get; set; }
        public int HouseHoldId { get; set; }
        public int CategoryId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Household Household { get; set; }
    }
}
