//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTemplate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insight_SchemaRegistry
    {
        public string SchemaGroup { get; set; }
        public string ObjectName { get; set; }
        public string Signature { get; set; }
        public string Type { get; set; }
        public Nullable<int> OriginalOrder { get; set; }
    }
}
